apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: slvqx8c19-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-qe-jsmid/slvqx8c19-java-quarkus-gitops